WorkHelper.WebUI/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkHelper.BLL.Interfaces;

namespace WorkHelper.WebUI.Controllers
{
    public class EmployeesController : Controller
    {
        private IEmployeeService employeeService;

        public EmployeesController(IEmployeeService employeeService)
        {
            this.employeeService = employeeService;
        }

        // GET: Employees
        public ActionResult Index()
        {
            return View(employeeService.GetEmployees());
        }

        protected override void Dispose(bool disposing)
        {
            employeeService.Dispose();
            base.Dispose(disposing);
        }
    }
}

WorkHelper.WebUI/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkHelper.WebUI.Controllers
{
    public class FormsController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }
    }
}

WorkHelper.WebUI/Views/Employees/Index.cshtml
@model IEnumerable<WorkHelper.BLL.DTO.EmployeeDTO>

@{
    ViewBag.Title = "Сотрудники";
}

<h2>Сотрудники</h2>

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>Ф.И.О.</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.FullName</td>
            </tr>
        }
    </tbody>
</table>

WorkHelper.WebUI/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Формы</h2>

WorkHelper.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Помощник в работе</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Формы <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("ОКУД", "Index", "Forms", new { type = 1 }, null)</li>
                            <li>@Html.ActionLink("ЭДОК", "Index", "Forms", new { type = 2 }, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Сотрудники", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Изменения", "Index", "Changes")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Отдел информатизации</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>